baseURL = "https://juicemia.com/"
languageCode = "en-us"
title = "8-BIT BITES"
theme = "retrofulhugo"

[Author]
    handle = "juice"
    name = "Hugo"
    github = "juicemia"
    twitter = "_juicemia"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
