baseurl = "http://juicemia.com"
languageCode = "en-us"
title = "juice"
theme = "purehugo"

[params]
  twitterName = "_juicemia"
  githubName = "HugoSTorres"
  description = "software soliloquies"
  hideShareOptions = true