baseURL = "https://juicemia.com/"
languageCode = "en-us"
title = "8-bit bites"
theme = "hello-friend"

[params.logo]
    logoText = "juice #"

[[menu.main]]
    name = "About"
    url = "/about/"

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/juicemia"

[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/@_juicemia"
